/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'ko' at '24/08/13 20:46' with Gradle 1.7
 *
 * @author ko, @date 24/08/13 20:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
